#!/usr/bin/env node
/**
 * Generates src/models/schemaMeta.js from the backend OpenAPI document.
 *
 * The API is ASP.NET, which emits every non-nullable property into `required`.
 * That makes `required` alone useless as a "the user must fill this in" signal,
 * so the generator also records nullability, taken from OpenAPI 3.1 type arrays
 * (`"type": ["null", "string"]`) since the 3.0 `nullable` key is never present.
 * src/models/requiredFields.js turns that raw metadata into the set the forms
 * actually enforce.
 *
 * Usage:
 *   node scripts/generate_schema_meta.js          # use the checked-in openapi.json
 *   node scripts/generate_schema_meta.js --live   # refresh openapi.json from the server first
 */
import { readFile, writeFile, copyFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SPEC_PATH = path.join(ROOT, 'openapi.json')
const PUBLIC_SPEC_PATH = path.join(ROOT, 'public', 'openapi.json')
const OUT_PATH = path.join(ROOT, 'src', 'models', 'schemaMeta.js')
const LIVE_URL = 'https://103.249.198.43:8090/openapi/v1.json'

async function refreshFromServer() {
  // The API serves a self-signed certificate; this is a local build step, not runtime.
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
  console.log(`Fetching ${LIVE_URL} ...`)
  const res = await fetch(LIVE_URL)
  if (!res.ok) throw new Error(`Live fetch failed: HTTP ${res.status}`)
  const text = await res.text()
  JSON.parse(text) // fail loudly rather than writing a corrupt spec
  await writeFile(SPEC_PATH, text)
  console.log(`Wrote ${path.relative(ROOT, SPEC_PATH)} (${text.length} bytes)`)
}

/** OpenAPI 3.1 encodes nullability as "null" inside a type array. */
const isNullable = (prop) => Array.isArray(prop?.type) && prop.type.includes('null')

/**
 * Walks `paths` to map each endpoint to its Create/Update request schema,
 * rather than hardcoding a table that would drift from the API.
 */
function mapEndpointsToSchemas(spec) {
  const map = {}
  for (const [routePath, operations] of Object.entries(spec.paths || {})) {
    const segments = routePath.split('/')
    if (segments.length < 3 || segments[1] !== 'api') continue
    const endpoint = segments[2]

    for (const [method, operation] of Object.entries(operations)) {
      if (!['post', 'put', 'patch'].includes(method)) continue
      // Skip sub-actions like /api/BillingDetails/generate-billing; only the
      // collection POST and the /{id} PUT describe the record itself.
      if (segments.length > 3 && !segments[3].startsWith('{')) continue

      const content = operation.requestBody?.content || {}
      let ref = null
      for (const media of Object.values(content)) {
        if (media?.schema?.$ref) {
          ref = media.schema.$ref.split('/').pop()
          break
        }
      }
      if (!ref) continue

      map[endpoint] = map[endpoint] || {}
      map[endpoint][method === 'post' ? 'create' : 'update'] = ref
    }
  }
  return map
}

function buildMeta(spec) {
  const schemas = spec.components?.schemas || {}
  const endpointSchemas = mapEndpointsToSchemas(spec)
  const meta = {}

  for (const endpoint of Object.keys(endpointSchemas).sort()) {
    const entry = {}
    for (const mode of ['create', 'update']) {
      const schemaName = endpointSchemas[endpoint][mode]
      if (!schemaName || !schemas[schemaName]) continue

      const schema = schemas[schemaName]
      const required = new Set(schema.required || [])

      // Keep only the properties the API genuinely cannot accept as empty:
      // flagged required AND not nullable. This stays small enough to import
      // from DynamicApiTable, which loads on nearly every route.
      const mandatory = Object.entries(schema.properties || {})
        .filter(([name, prop]) => required.has(name) && !isNullable(prop))
        .map(([name]) => name)

      entry[mode] = { schema: schemaName, required: mandatory }
    }
    if (Object.keys(entry).length) meta[endpoint] = entry
  }

  return meta
}

async function main() {
  if (process.argv.includes('--live')) await refreshFromServer()

  const spec = JSON.parse(await readFile(SPEC_PATH, 'utf8'))
  const meta = buildMeta(spec)

  const banner = `// AUTO-GENERATED by scripts/generate_schema_meta.js — do not edit by hand.
// Run \`npm run gen:schema\` (add --live to pull a fresh spec from the API) to regenerate.
//
// Source: ${spec.info?.title || 'API'} v${spec.info?.version || '?'} (OpenAPI ${spec.openapi})
//
// \`required\` is every property the API flags required AND types as non-nullable.
// The backend marks all non-nullable properties required, so these lists are far
// broader than what a form should actually enforce — src/models/requiredFields.js
// narrows them down with system-field exclusions and per-endpoint overrides.
//
// The full spec (types, formats, every property) lives in public/openapi.json,
// which the Models page fetches at runtime so it stays out of the JS bundle.

`

  await writeFile(OUT_PATH, `${banner}export const EndpointSchemaMeta = ${JSON.stringify(meta, null, 2)}\n\nexport default EndpointSchemaMeta\n`)
  await copyFile(SPEC_PATH, PUBLIC_SPEC_PATH)

  const endpoints = Object.keys(meta)
  console.log(`Wrote ${path.relative(ROOT, OUT_PATH)} — ${endpoints.length} endpoints`)
  console.log(`Copied spec to ${path.relative(ROOT, PUBLIC_SPEC_PATH)}`)
}

main().catch(err => {
  console.error(err.message)
  process.exit(1)
})
