// AUTO-GENERATED by scripts/generate_schema_meta.js — do not edit by hand.
// Run `npm run gen:schema` (add --live to pull a fresh spec from the API) to regenerate.
//
// Source: App.Api | v1 v1.0.0 (OpenAPI 3.1.1)
//
// `required` is every property the API flags required AND types as non-nullable.
// The backend marks all non-nullable properties required, so these lists are far
// broader than what a form should actually enforce — src/models/requiredFields.js
// narrows them down with system-field exclusions and per-endpoint overrides.
//
// The full spec (types, formats, every property) lives in public/openapi.json,
// which the Models page fetches at runtime so it stays out of the JS bundle.

export const EndpointSchemaMeta = {
  "AccessLevel": {
    "create": {
      "schema": "CreateAccessLevelRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateLcpRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "AccesslevelMenu": {
    "create": {
      "schema": "CreateAccesslevelMenuRequest",
      "required": [
        "menu_id",
        "accesslevel_id"
      ]
    },
    "update": {
      "schema": "UpdateAccesslevelMenuRequest",
      "required": [
        "menu_id",
        "accesslevel_id"
      ]
    }
  },
  "Applications": {
    "create": {
      "schema": "CreateApplicationRequest",
      "required": [
        "timestamp",
        "emailAddress",
        "region",
        "city",
        "barangay",
        "referredBy",
        "firstName",
        "middleName",
        "lastName",
        "mobileNumber",
        "secondaryMobileNumber",
        "installationAddress",
        "landmark",
        "desiredPlan",
        "proofOfBilling",
        "governmentValidId",
        "secondGovernmentValidId",
        "houseFrontPicture",
        "termsAndConditionsAgreement",
        "firstNearestLandmark",
        "secondNearestLandmark",
        "applicablePromo",
        "documentPicture",
        "barangay1",
        "barangay2",
        "pictureofstatmentbillingfromotherprovider",
        "referrersAccountNumber",
        "applyingFor",
        "status",
        "visitBy",
        "visitWith",
        "visitWithOther",
        "remarks",
        "modifiedBy",
        "modifiedDate",
        "userEmail"
      ]
    },
    "update": {
      "schema": "UpdateApplicationRequest",
      "required": [
        "emailAddress",
        "region",
        "city",
        "barangay",
        "referredBy",
        "firstName",
        "middleName",
        "lastName",
        "mobileNumber",
        "secondaryMobileNumber",
        "installationAddress",
        "landmark",
        "desiredPlan",
        "proofOfBilling",
        "governmentValidId",
        "secondGovernmentValidId",
        "houseFrontPicture",
        "termsAndConditionsAgreement",
        "firstNearestLandmark",
        "secondNearestLandmark",
        "applicablePromo",
        "documentPicture",
        "barangay1",
        "barangay2",
        "pictureofstatmentbillingfromotherprovider",
        "referrersAccountNumber",
        "applyingFor",
        "status",
        "visitBy",
        "visitWith",
        "visitWithOther",
        "remarks",
        "modifiedBy",
        "modifiedDate",
        "userEmail"
      ]
    }
  },
  "Barangays": {
    "create": {
      "schema": "CreateBarangayRequest",
      "required": [
        "name",
        "city"
      ]
    },
    "update": {
      "schema": "UpdateBarangayRequest",
      "required": [
        "name",
        "city"
      ]
    }
  },
  "BillingDetails": {
    "create": {
      "schema": "CreateBillingDetailsRequest",
      "required": [
        "fullName",
        "contactNumber",
        "emailAddress",
        "address",
        "location",
        "plan",
        "provider",
        "username",
        "connectionType",
        "routerModemSn",
        "ip",
        "lcp",
        "nap",
        "port",
        "vlan",
        "lcpNap",
        "status",
        "group",
        "modifiedBy",
        "userEmail",
        "billingStatus",
        "deliveryStatus",
        "routerModel",
        "barangay",
        "city",
        "region",
        "lcpNapPort",
        "usageType",
        "renter",
        "attachment1",
        "attachment2",
        "attachment3",
        "referredBy",
        "secondContactNumber",
        "addressCoordinates",
        "referrersAccountNumber"
      ]
    },
    "update": {
      "schema": "UpdateBillingDetailsRequest",
      "required": [
        "fullName",
        "contactNumber",
        "emailAddress",
        "address",
        "location",
        "plan",
        "provider",
        "username",
        "connectionType",
        "routerModemSn",
        "ip",
        "lcp",
        "nap",
        "port",
        "vlan",
        "lcpNap",
        "status",
        "group",
        "modifiedBy",
        "userEmail",
        "billingStatus",
        "deliveryStatus",
        "routerModel",
        "barangay",
        "city",
        "region",
        "lcpNapPort",
        "usageType",
        "renter",
        "attachment1",
        "attachment2",
        "attachment3",
        "referredBy",
        "secondContactNumber",
        "addressCoordinates",
        "referrersAccountNumber"
      ]
    }
  },
  "BillingStatuses": {
    "create": {
      "schema": "BillingStatus",
      "required": []
    },
    "update": {
      "schema": "BillingStatus",
      "required": []
    }
  },
  "Invoice": {
    "create": {
      "schema": "InvoiceDto",
      "required": []
    },
    "update": {
      "schema": "InvoiceDto",
      "required": []
    }
  },
  "Invoices": {
    "create": {
      "schema": "InvoiceDto",
      "required": []
    },
    "update": {
      "schema": "InvoiceDto",
      "required": []
    }
  },
  "JobOrders": {
    "create": {
      "schema": "CreateJobOrderRequest",
      "required": [
        "emailAddress",
        "referredBy",
        "firstName",
        "middleInitial",
        "lastName",
        "contactNumber",
        "applicantEmailAddress",
        "address",
        "location",
        "barangay",
        "city",
        "region",
        "planId",
        "remarks",
        "installationFee",
        "contractTemplate",
        "billingDay",
        "preferredDay",
        "joRemarks",
        "status",
        "verifiedBy",
        "modemRouterSN",
        "provider",
        "portId",
        "username",
        "visitBy",
        "visitWith",
        "visitWithOther",
        "onsiteStatus",
        "onsiteRemarks",
        "modifiedBy",
        "contractLink",
        "connectionType",
        "assignedEmail",
        "setupImage",
        "speedtestImage",
        "duration",
        "externalId",
        "lcpnapId",
        "billingStatus",
        "routerModel",
        "clientSignature",
        "ip",
        "signedContractImage",
        "boxReadingImage",
        "routerReadingImage",
        "usernameStatus",
        "lcpnapportId",
        "itemName1",
        "itemQuantity1",
        "itemName2",
        "itemQuantity2",
        "itemName3",
        "itemQuantity3",
        "itemName4",
        "itemQuantity4",
        "itemName5",
        "itemQuantity5",
        "itemName6",
        "itemQuantity6",
        "itemName7",
        "itemQuantity7",
        "itemName8",
        "itemQuantity8",
        "itemName9",
        "itemQuantity9",
        "itemName10",
        "itemQuantity10",
        "usageType",
        "renter",
        "installationLandmark",
        "statusRemarks",
        "portLabelImage",
        "secondContactNumber",
        "accountNo",
        "addressCoordinates",
        "referrersAccountNumber",
        "applicationId",
        "houseFront"
      ]
    },
    "update": {
      "schema": "UpdateJobOrderRequest",
      "required": [
        "emailAddress",
        "referredBy",
        "firstName",
        "middleInitial",
        "lastName",
        "contactNumber",
        "applicantEmailAddress",
        "address",
        "location",
        "barangay",
        "city",
        "region",
        "planId",
        "remarks",
        "installationFee",
        "contractTemplate",
        "billingDay",
        "preferredDay",
        "joRemarks",
        "status",
        "verifiedBy",
        "modemRouterSN",
        "provider",
        "lcpId",
        "napId",
        "portId",
        "vlanId",
        "username",
        "visitBy",
        "visitWith",
        "visitWithOther",
        "onsiteStatus",
        "onsiteRemarks",
        "modifiedBy",
        "contractLink",
        "connectionType",
        "assignedEmail",
        "setupImage",
        "speedtestImage",
        "duration",
        "externalId",
        "lcpnapId",
        "billingStatus",
        "routerModel",
        "clientSignature",
        "ip",
        "signedContractImage",
        "boxReadingImage",
        "routerReadingImage",
        "usernameStatus",
        "lcpnapportId",
        "itemName1",
        "itemQuantity1",
        "itemName2",
        "itemQuantity2",
        "itemName3",
        "itemQuantity3",
        "itemName4",
        "itemQuantity4",
        "itemName5",
        "itemQuantity5",
        "itemName6",
        "itemQuantity6",
        "itemName7",
        "itemQuantity7",
        "itemName8",
        "itemQuantity8",
        "itemName9",
        "itemQuantity9",
        "itemName10",
        "itemQuantity10",
        "usageType",
        "renter",
        "installationLandmark",
        "statusRemarks",
        "portLabelImage",
        "secondContactNumber",
        "accountNo",
        "addressCoordinates",
        "referrersAccountNumber",
        "applicationId",
        "houseFront"
      ]
    }
  },
  "LCPNapLocations": {
    "create": {
      "schema": "CreateLCPNapLocationCommand",
      "required": []
    },
    "update": {
      "schema": "UpdateLCPNapLocationCommand",
      "required": [
        "id"
      ]
    }
  },
  "Lcpnapports": {
    "create": {
      "schema": "CreateLcpnapportRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateLcpnapportRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Lcpnaps": {
    "create": {
      "schema": "CreateLcpnapRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateLcpnapRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Lcps": {
    "create": {
      "schema": "CreateLcpRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateLcpRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Menus": {
    "create": {
      "schema": "CreateMenuRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateMenuRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Naps": {
    "create": {
      "schema": "CreateNapRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateNapRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Plans": {
    "create": {
      "schema": "PlanDto",
      "required": []
    },
    "update": {
      "schema": "PlanDto",
      "required": []
    }
  },
  "Ports": {
    "create": {
      "schema": "CreatePortsRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdatePortRequest",
      "required": [
        "name",
        "description"
      ]
    }
  },
  "Routers": {
    "create": {
      "schema": "CreateRouterRequest",
      "required": [
        "name",
        "description",
        "brand",
        "model"
      ]
    },
    "update": {
      "schema": "UpdateRouterRequest",
      "required": [
        "name",
        "description",
        "brand",
        "model"
      ]
    }
  },
  "ServiceOrders": {
    "create": {
      "schema": "CreateServiceOrderRequest",
      "required": []
    },
    "update": {
      "schema": "UpdateServiceOrderRequest",
      "required": []
    }
  },
  "Token": {
    "create": {
      "schema": "RevokeTokenRequest",
      "required": []
    }
  },
  "Users": {
    "create": {
      "schema": "CreateUserRequest",
      "required": [
        "fname",
        "lname",
        "contactnumber",
        "address",
        "email",
        "username",
        "password",
        "active"
      ]
    },
    "update": {
      "schema": "UpdateUserRequest",
      "required": [
        "fname",
        "lname",
        "contactnumber",
        "address",
        "email",
        "username",
        "password",
        "active"
      ]
    }
  },
  "Vlans": {
    "create": {
      "schema": "CreateVlanRequest",
      "required": [
        "name",
        "description"
      ]
    },
    "update": {
      "schema": "UpdateVlanRequest",
      "required": [
        "name",
        "description"
      ]
    }
  }
}

export default EndpointSchemaMeta
